doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                dbname: '%env(resolve:MYSQL_DATABASE)%'
                user: '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
                host: '%env(resolve:MYSQL_HOST)%'
                port: '%env(resolve:MYSQL_PORT)%'
                server_version: '5.7'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
