version: '3.9'

services:
  php:
    image: vdmitriev/vdmitriev-lamoda-test/php:latest
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/var/www:rw,cached
  nginx:
    image: vdmitriev/vdmitriev-lamoda-test/nginx:latest
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    links:
      - php
    ports:
      - "8080:80"
  db:
    image: mysql:8.0.21
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3315:3306"
volumes:
  data: