# As of Symfony 5.1, deprecations are logged in the dedicated "deprecation" channel when it exists
#monolog:
#    channels: [deprecation]
#    handlers:
#        deprecation:
#            type: stream
#            channels: [deprecation]
#            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
monolog:
  handlers:
    main:
      type: stream
      path: "php://stdout"
      level: debug
      channels: ["!event"]
      formatter: logger.json_formatter
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
