monolog:
  handlers:
    main:
      type: stream
      path: "php://stdout"
      level: debug
      channels: ["!event"]
      formatter: logger.json_formatter
    console:
      type: console
      process_psr_3_messages: false
      channels: ["!event", "!doctrine", "!console"]
